swagger: "2.0"
info:
  description: Test task for job application
  version: 1.0.0
  title: Swagger Test Task
host: localhost:3000
basePath: /api/v1
tags:
  - name: movies
    description: Movies list
schemes:
  - https
  - http
paths:
  /movies:
    x-swagger-router-controller: movies
    get:
      tags:
        - movies
      summary: Finds movies by query
      description: Find movies by genre and/or year using query
      operationId: findMovies
      produces:
        - application/json
      parameters:
        - in: query
          name: size
          type: integer
          required: false
          default: 10
        - in: query
          type: integer
          name: from
          required: false
        - in: query
          type: array
          items:
            type: string
          name: genres
          required: false
        - in: query
          type: array
          items:
            type: number
          name: years
          required: false
        - in: query
          type: boolean
          name: strict
          required: false
      responses:
        "200":
          description: successful operation
          schema:
            $ref: "#/definitions/Response"
        "400":
          description: Invalid query value
          schema:
            $ref: "#/definitions/Status"

definitions:
  Status:
    type: object
    properties:
      code:
        type: number
      message:
        type: string
  Response:
    type: object
    properties:
      size:
        type: number
      data:
        type: array
        items:
          $ref: "#/definitions/Movie"
      status:
        $ref: "#/definitions/Status"
  Movie:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
      genre1:
        type: string
      genre2:
        type: string
      year:
        type: integer
        minimum: 1800
        maximum: 2100
